#!/usr/bin/env python3
"""
Print all AcroForm field IDs from the extracted charsheet_fields.json and
generate a ready-to-edit sheet_bindings.json template.

Usage
-----
    # With a fields.json already generated by extract_fields.py:
    python3 tools/dump_fields.py

    # Or point it at a specific JSON:
    python3 tools/dump_fields.py path/to/charsheet_fields.json

    # Write a bindings template to disk instead of stdout:
    python3 tools/dump_fields.py --write-template

After running this, copy sheet_bindings.json to the project root and fill in
the "binding" value for each field you want auto-calculated.  Then rebuild:
    cargo build --release

Binding key reference
---------------------
Basic stats:
    profBonus          level              xp

Ability scores (number):
    strScore  dexScore  conScore  intScore  wisScore  chaScore

Ability modifiers (number, e.g. 3):
    strMod  dexMod  conMod  intMod  wisMod  chaMod

Ability modifiers (formatted with sign, e.g. "+3" / "-1"):
    strModFmt  dexModFmt  conModFmt  intModFmt  wisModFmt  chaModFmt

Hit points:
    maxHp       currentHp    tempHp
    hpDisplay   (e.g. "15/20 + 3 temp")

Combat:
    armorClass  speed   initiative  initiativeFmt

Passive skills:
    passivePerception   passiveInvestigation

Spellcasting:
    spellSaveDc   spellAttackBonus   spellAttackBonusFmt

Skill bonuses by index 0-17  (Acrobatics…Survival, PHB alphabetical order):
    skillBonus:0   skillBonus:1   … skillBonus:17
    skillBonusFmt:0 … skillBonusFmt:17   (with sign: "+5")

Saving throw bonuses by index 0-5  (STR DEX CON INT WIS CHA):
    saveBonus:0  saveBonus:1  saveBonus:2  saveBonus:3  saveBonus:4  saveBonus:5
    saveBonusFmt:0 … saveBonusFmt:5

Named skill shortcuts:
    skill:Acrobatics    skill:AnimalHandling  skill:Arcana      skill:Athletics
    skill:Deception     skill:History         skill:Insight     skill:Intimidation
    skill:Investigation skill:Medicine        skill:Nature      skill:Perception
    skill:Performance   skill:Persuasion      skill:Religion    skill:SleightOfHand
    skill:Stealth       skill:Survival

Named save shortcuts:
    save:STR  save:DEX  save:CON  save:INT  save:WIS  save:CHA
"""

import argparse
import json
import sys
from pathlib import Path

SKILL_NAMES = [
    "Acrobatics", "AnimalHandling", "Arcana", "Athletics", "Deception",
    "History", "Insight", "Intimidation", "Investigation", "Medicine",
    "Nature", "Perception", "Performance", "Persuasion", "Religion",
    "SleightOfHand", "Stealth", "Survival",
]
ABILITY_ABBREVS = ["STR", "DEX", "CON", "INT", "WIS", "CHA"]


def find_fields_json() -> Path:
    """Search standard locations for charsheet_fields.json."""
    candidates = [
        Path(__file__).parent.parent / "assets" / "charsheet_fields.json",
        Path("assets") / "charsheet_fields.json",
        Path("charsheet_fields.json"),
    ]
    for p in candidates:
        if p.exists():
            return p
    return None


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Dump PDF field IDs and generate a sheet_bindings.json template.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "json_file",
        nargs="?",
        help="Path to charsheet_fields.json (auto-detected if omitted)",
    )
    parser.add_argument(
        "--write-template",
        action="store_true",
        help="Write sheet_bindings.json template to the project root",
    )
    args = parser.parse_args()

    if args.json_file:
        json_path = Path(args.json_file)
    else:
        json_path = find_fields_json()

    if json_path is None or not json_path.exists():
        sys.exit(
            "charsheet_fields.json not found.  Either:\n"
            "  1. Place sheet.pdf in the project root and run: cargo build\n"
            "  2. Run: python3 tools/extract_fields.py path/to/sheet.pdf\n"
            "  3. Pass the path explicitly: python3 tools/dump_fields.py path/to/fields.json"
        )

    fields = json.loads(json_path.read_text())

    # ── Print field table ──────────────────────────────────────────────────
    id_w = max((len(f["id"]) for f in fields), default=10)
    label_w = max((len(f.get("label", "")) for f in fields), default=10)
    id_w = max(id_w, 8)
    label_w = max(label_w, 5)

    print(f"\n{'Field ID':<{id_w}}  {'Label':<{label_w}}  Type      Approx size")
    print(f"{'-'*id_w}  {'-'*label_w}  --------  -----------")
    for f in fields:
        w_pct = round(f["w"] * 100)
        h_pct = round(f["h"] * 100)
        size = f"~{w_pct}%×{h_pct}%"
        print(f"{f['id']:<{id_w}}  {f.get('label',''):<{label_w}}  {f['type']:<8}  {size}")

    print(f"\nTotal: {len(fields)} fields from {json_path}\n")

    # ── Generate template ──────────────────────────────────────────────────
    # Build a mapping with null for all fields (user fills in the binding key).
    template: dict = {}

    # Try to auto-guess common official D&D 5e WotC sheet field names.
    auto_map = _auto_guess({f["id"] for f in fields})
    for f in fields:
        template[f["id"]] = auto_map.get(f["id"])  # None if no guess

    template_json = json.dumps(template, indent=2)

    if args.write_template:
        out = Path(__file__).parent.parent / "sheet_bindings.json"
        out.write_text(template_json)
        print(f"Wrote template: {out}")
        print("Edit the null values with binding keys (see --help for the key reference).")
    else:
        print("── Template sheet_bindings.json ──────────────────────────────────────")
        print("(run with --write-template to save to disk)\n")
        print(template_json)
        print()
        if any(v is not None for v in template.values()):
            guessed = [(k, v) for k, v in template.items() if v is not None]
            print(f"Auto-guessed {len(guessed)} binding(s) based on common D&D 5e field names:")
            for k, v in guessed:
                print(f"  {k!r:40} → {v!r}")
            print()


def _auto_guess(field_ids: set) -> dict:
    """Heuristic map for the official WotC D&D 5e fillable PDF field names."""
    # Based on the standard 5e character sheet AcroForm names.
    known = {
        # Identity
        "CharacterName":        "level",        # often char name; leave as ink
        "CharacterName 2":      None,
        # These are from the official WotC/5e sheet
        "HPMax":                "maxHp",
        "HPCurrent":            "currentHp",
        "HPTemp":               "tempHp",
        "AC":                   "armorClass",
        "Initiative":           "initiativeFmt",
        "Speed":                "speed",
        "ProfBonus":            "profBonus",
        "Passive":              "passivePerception",
        # Ability scores
        "STR":                  "strScore",
        "DEX":                  "dexScore",
        "CON":                  "conScore",
        "INT":                  "intScore",
        "WIS":                  "wisScore",
        "CHA":                  "chaScore",
        # Modifiers
        "STRmod":               "strModFmt",
        "DEXmod ":              "dexModFmt",
        "CONmod":               "conModFmt",
        "INTmod":               "intModFmt",
        "WISmod":               "wisModFmt",
        "CHamod":               "chaModFmt",
        # Saving throws
        "ST Strength":          "saveBonusFmt:0",
        "ST Dexterity":         "saveBonusFmt:1",
        "ST Constitution":      "saveBonusFmt:2",
        "ST Intelligence":      "saveBonusFmt:3",
        "ST Wisdom":            "saveBonusFmt:4",
        "ST Charisma":          "saveBonusFmt:5",
        # Skills (WotC official names)
        "Acrobatics":           "skillBonusFmt:0",
        "Animal":               "skillBonusFmt:1",
        "Arcana":               "skillBonusFmt:2",
        "Athletics":            "skillBonusFmt:3",
        "Deception ":           "skillBonusFmt:4",
        "History ":             "skillBonusFmt:5",
        "Insight":              "skillBonusFmt:6",
        "Intimidation":         "skillBonusFmt:7",
        "Investigation ":       "skillBonusFmt:8",
        "Medicine":             "skillBonusFmt:9",
        "Nature":               "skillBonusFmt:10",
        "Perception ":          "skillBonusFmt:11",
        "Performance":          "skillBonusFmt:12",
        "Persuasion":           "skillBonusFmt:13",
        "Religion":             "skillBonusFmt:14",
        "SleightofHand":        "skillBonusFmt:15",
        "Stealth ":             "skillBonusFmt:16",
        "Survival":             "skillBonusFmt:17",
        # Spellcasting
        "SpellSaveDC":          "spellSaveDc",
        "SpellAtkBonus":        "spellAttackBonusFmt",
        # Level/XP
        "XP":                   "xp",
        "Level":                "level",
        "TotalLevel":           "level",
    }
    return {k: v for k, v in known.items() if k in field_ids}


if __name__ == "__main__":
    main()
